---
# task/prerequisites file for renew_vault_certificates
- name: "Install required roles"
  ansible.builtin.command:
    cmd: "ansible-galaxy install {{ item }}"
  loop: "{{ renew_vault_certificates_prerequisites_roles }}"
  changed_when: false
  delegate_to: localhost
  run_once: true

- name: "Create directory {{ renew_vault_certificates_config_dir }}"
  ansible.builtin.file:
    path: "{{ renew_vault_certificates_config_dir }}"
    state: directory
    owner: "{{ renew_vault_certificates_vault_user }}"
    group: "{{ renew_vault_certificates_vault_group }}"
    mode: '0755'

- name: "Create directory {{ renew_vault_certificates_config_dir }}/templates"
  ansible.builtin.file:
    path: "{{ renew_vault_certificates_config_dir }}/templates"
    state: directory
    owner: "{{ renew_vault_certificates_vault_user }}"
    group: "{{ renew_vault_certificates_vault_group }}"
    mode: '0755'
