---
dependency:
  name: galaxy
  options:
    requirements-file: ./requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    box: generic/${MOLECULE_TEST_OS}
    cpus: 4
    memory: 4096
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
verifier:
  name: ansible
scenario:
  name: with_custom_config_vagrant
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
