---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Include ednz_cloud.renew_vault_certificates"
      ansible.builtin.include_role:
        name: "ednz_cloud.renew_vault_certificates"
