---
dependency:
  name: galaxy
  options:
    requirements-file: ./requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_TEST_OS}-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
verifier:
  name: testinfra
lint: |
  yamllint -c .yamllint .
  ansible-lint
scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
