---
name: publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish
        uses: ednxzu/galaxy-import-role@v1
        with:
          galaxy-api-key: ${{ secrets.GALAXY_API_TOKEN }}
